### ISSUE TITLE
My ideas for Polish region

### ISSUE THREAD

**Issue by KubaFracek** [vikingnephilim/VikingShattered#1]
Hi, viking

I started playing Wielkopolska and noticed a few problems.
1. Wielkopolska, Małopolska, Kraków, Kujawy should be duchies
2. Kashubian culture should be in Tuchola and Gdańsk in Polish culture group
3. Lithuania and Hungary should be Poland's historical friends
4. Chełmno should be needed to create Poland
5. Krakow and Danzig does not have a ruler in the opening screen https://imgur.com/a/PRRVFiG

**Comment by vikingnephilim** [comment]
Hi 

Thank You. Below are my answers to your points. 

1 - what rank are they now? I'll adjust to duchies without an issue. 

2 - if it's a single province culture, I won't add it, it would need to be 5 or more to consider it. So if there are others, then please list. 

3 - all starting alliances, subjects etc have been removed. Historic friendships and such are in game, but they no longer determine alliance chains etc. 

4 - I will adjust the decision accordingly. Thank you. 

5 - can you think of names for the rulers? Unfortunately I've taken on a host of no ruler nations when agreeing to this project. I am happy to listen to all ruler names, and dynasties. 

Thank you.

**Comment by vikingnephilim** [comment]
1 - Government ranks have been adjusted and merged
4 - decision has been adjusted to add Chelmno province into formation of Poland

**Comment by vikingnephilim** [comment]
with regards to 5, I've had a look around online, and assigned a couple of rulers in the Polish region using random names from the Polish name set :)
