### ISSUE TITLE
Polynesian mission tree bug

### ISSUE THREAD

**Issue by horde-enthusiast** [vikingnephilim/VikingShattered#14]
![mission broke](https://user-images.githubusercontent.com/69428534/89736066-bcf25300-da5e-11ea-8d18-cfba19d222f1.png)!

**Comment by vikingnephilim** [comment]
Thank you. I'll fix this mission. For the MP it won't be fixed but for the next MP it will be. Should have a version available tomorrow built.

**Comment by vikingnephilim** [comment]
this has been fixed and will be updated with the next update :)
