### ISSUE TITLE
Iroquois Nation suggestion

### ISSUE THREAD

**Issue by Maned-Wolf** [vikingnephilim/VikingShattered#15]
Iroquois confederacy should instead start as five separate opms, west to east being Seneca, Cayuga, Onondaga, Oneida, and Mohawk. Originally peacefully confederated at an estimated 1500-1600 (records are unclear and have lapsed into legend). All spoke the same language and had roughly similar cultures. After confederation had a historical rivalry with french-backed Huron.

I'm not totally sure how the idea sets should work, but Seneca was historically the most diplomatically inclined and their members often held leadership of the confederation. Mohawk (yes, that is where the hairstyle comes from) were by far the most warlike of the five and were most responsible for defense against the europeans (which succeeded until a short time after the 7 years war (british side)) 

This could be an untenable addition, but i thought that we should also show some historical love to the new world.

**Comment by vikingnephilim** [comment]
Hi. Thanks for this. It won't be something I'll implement I don't think. Purely on the basis I've removed all of the alliances and such at the start of the game. As a result, setting up a federation wouldn't be in my interest. However, this is a suggestion I think you should put on the paradox forums and make the suggestion to them.

I appreciate the thought though. If I do decide anything for new world love, I am happy to add new cultures, new tags and such like, but being so close to each other, I think it would be a nightmare.
