### ISSUE TITLE
Valencia Culture

### ISSUE THREAD

**Issue by Feuerhai** [vikingnephilim/VikingShattered#18]
After conquering Valencia I was not able to release them again, so I think they're somehow not in the Iberian culture group. I can check after the game.

**Comment by Feuerhai** [comment]
Just checked, Valencia still has Catalan as it's primary Culture, which is in the Montagne French group and not Valenciano, which is the culture that all of their provinces have.

**Comment by vikingnephilim** [comment]
Thanks for highlighting. I will correct that on the tags

**Comment by vikingnephilim** [comment]
I have corrected the tags.

Asturias is now Asturian culture primary
Majorca is Balearic culture primary
Catalunya has Catalan culture primary
Valencia has Valenciano culture primary :)
