### ISSUE TITLE
Government Expanded side bonuses that do not work

### ISSUE THREAD

**Issue by Findeath** [vikingnephilim/VikingShattered#26]
Monarchy:
T2: Diplomatic Positions - Does not show a Privilege from the noble estate
T2: Papal Embassy - Does not give a +25 opinion with the pope like it states
T2: Portuguese Cortes - Does not give a noble Privilege which apparently has some flavour?
T4: Professional Army - Does not give 25% extra army professionalism for recruiting a general
T4: National Guard - Does not appear to give 25% extra manpower from Primary Culture land (Stockholm remained at 750 manpower at start)
T4: Empowered Heavy Knights - Do not need to have Aristocratic fully filled out for 5% shock damage to be applied (Might be a bug but not too important)
T5: Empowered Nobles of the Robe - Army Tradition Per general works but no noble privilege exists for better generals per generation.
T6: Parliamentary Order (Swedish, Geats and Scanian exclusive gov) - No Peasants Estate shows up

Republican:
T7: Empowered Consolidation of Power - Does not give 2 Absolutism per re-election
T7: Empowered Aristocratic Courts - Does not have Magnate Law Privilege for Nobles giving -2.5 National Unrest

Theocracies:
T10: Holy War - Does not enable bordering holy wars on heretic/heathen nations
T11: Unrestricted Diplomacy - Does not give +25 relations with everyone known

These are all I had time to find tonight. Will find more later.

**Comment by vikingnephilim** [comment]
T2 - Diplomatic Positions - Fixed
T2 - Papal Embassy - Fixed
T2 - Portuguese Cortes - Fixed
