### ISSUE TITLE
RuthenianNation.txt decision uses legacy culture Ruthenian/Byelorussian

### ISSUE THREAD

**Issue by Thorfindel** [vikingnephilim/VikingShattered#27]
With the changes to Ruthenian cultures, the decision no longer works because Byelorussian/Ruthenian cultures don't exist anymore. 
Suggestions:
1. Add specific cultures white_ruthenian and black_ruthenian to potential
2. Add whole culture group ruthenian_group to potential

**Comment by vikingnephilim** [comment]
Fixed to be ruthenian group culture.
