### ISSUE TITLE
Cont. Governments expanded issues (All Monarchy)

### ISSUE THREAD

**Issue by Findeath** [vikingnephilim/VikingShattered#28]
T1: Ancien Regime - No idea how to get it
T1: Royaume du Soleil - See Ancien Regime
T1: Granadan Iqta - No way to get it besides starting as Granada
T2: Nobi Jongmobub - Does not show up for the Korean sub-cultures
T2: Invite Imperial Knights - Does not make an Imperial Knights Mercenary Company available to recruit
T2: Noblesse d'epee - Unknown location, cannot test this
T2: Taha Divisions - Does not show up for Islamic Spanish, can't test
T2: Support Ghibbellines & Support Guelphs - Not available/triggers unknown
T2: Timariot Domains - Turkish, Timariot Domains Privilege for nobility estate.
T2: Turkic Qasilbash Heirs - Persia, Does not show Qizilbash Mercenary company
T3: Kaza system - Turkish, no Trade efficiency is produced for any % of sunni land
T3: Reinforce Magdeburg Rights - No town Rights Privilege for burghers giving goods produced and dev cost % on land ownership (Requires Primary culture of Polish and 5 polish provences)
T3: Guidance of the Dalai Llama - Tibet, Does not give +2 unrest if Lhasa is not Vajrayana
T3: Administer the Imperial Circle - HRE based, town rights privilege does not show
T3: Bangyesurok - Same as the Nobi Jongmobub
T3: Levy the Thirthieth - cannot find source, suspect it to be either Romanians or Caucases, can't test goods produced on salt and naval
T4: Abolish the Patronage System - Cannot find it. cannot test enables_foreign_worship
T4: Royal Training - Source unknown, can't test Swiss Guard
T4: Arabian horses - Cannot find Arabian horses reform, tagged through many Arabian tags
T4: Berber Cavalry - Cannot find source
T4: Jaesungbangryak - Same as the Nobi Jongmobub
T5: Szlachta Recruits - Same issue with Nobles of the Robe with Noble officers Privilege for nobility
T5: Voivode Captains - See above with Szlachta
T5: Boyar Scions - See above with Szlachta
T5: Cultural Investment - Can't find when Andalusia
T5: Foreign Ghulams - Not found with Caucasian culture group, creates Ghulams estate
T5: Eunich Administration - MNG, Heavenly Court mechanic does not appear to work upon ruler coronation
T5: Civil Servant System - same as Eunich Administration
T5: Kiwi Support - Does not come up without Undang Undang Laut Melaka reform
T5: Korean Bureaucracy - same as Nobi Jongmobub
T5: Decretum Maius - Unknown Origin, can't test
T5: Corps Diplomatique - France, Requires Ultimate france T1, ally/guarantees/marriages do not get +20 bonus
T6: Noble Electors - Unknown Origins, can't test
T6: Royal Electors - Unknown Origins, can't test
T6: Parliamental Electors - Unknown Origins, can't test
T6: Papal Electors - Unknown Origins, can't test

**Comment by vikingnephilim** [comment]
##########################################FIXED##########################################
- T1: Ancien Regime - Fixed, Must be one of the French Culture groups or have french feudalism or royaume du soleil
- T1: Royaume du Soleil - Fixed, Must be one of the French Culture groups or have french feudalism or ancien regime
- T1: Granadan Iqta - Fixed. Must be Andalucian culture, Muslim religion and have Iqta already
- T2: Nobi Jongmobub - Fixed. Must be Korean culture group (which includes full korean)
- T2: Invite Imperial Knights - Fixed, Was relating to a GE bug. Replaced the Merc company with 10% reduced global merc maintenance.
- T2: Noblesse d'epee - Fixed. Was relating to Ancien Regime bug.
- T2: Taha Divisions - Fixed. Primary culture is now Andalucian and Muslim, with granadan iqta.
- T2: Support Ghibbellines & Support Guelphs - Removed from mod. The factions caused issues.
- T2: Timariot Domains - Fixed. Removed estate privilege, Added cavalry flanking ability +15%
- T2: Turkic Qasilbash Heirs - Fixed. Removed merc company. Replaced with 10% reduced global merc maintenance
##########################################TO DO##########################################

- T3: Kaza system - Turkish, no Trade efficiency is produced for any % of sunni land
- T3: Reinforce Magdeburg Rights - No town Rights Privilege for burghers giving goods produced and dev cost % on land ownership (Requires Primary culture of Polish and 5 polish provences)
- T3: Guidance of the Dalai Llama - Tibet, Does not give +2 unrest if Lhasa is not Vajrayana
- T3: Administer the Imperial Circle - HRE based, town rights privilege does not show
- T3: Bangyesurok - Same as the Nobi Jongmobub
- T3: Levy the Thirthieth - cannot find source, suspect it to be either Romanians or Caucases, can't test goods produced on salt and naval
- 
- T4: Abolish the Patronage System - Cannot find it. cannot test enables_foreign_worship
- T4: Royal Training - Source unknown, can't test Swiss Guard
- T4: Arabian horses - Cannot find Arabian horses reform, tagged through many Arabian tags
- T4: Berber Cavalry - Cannot find source
- T4: Jaesungbangryak - Same as the Nobi Jongmobub
- T5: Szlachta Recruits - Same issue with Nobles of the Robe with Noble officers Privilege for nobility
- T5: Voivode Captains - See above with Szlachta
- T5: Boyar Scions - See above with Szlachta
- T5: Cultural Investment - Can't find when Andalusia
- T5: Foreign Ghulams - Not found with Caucasian culture group, creates Ghulams estate
- T5: Eunich Administration - MNG, Heavenly Court mechanic does not appear to work upon ruler coronation
- T5: Civil Servant System - same as Eunich Administration
- T5: Kiwi Support - Does not come up without Undang Undang Laut Melaka reform
- T5: Korean Bureaucracy - same as Nobi Jongmobub
- T5: Decretum Maius - Unknown Origin, can't test
- T5: Corps Diplomatique - France, Requires Ultimate france T1, ally/guarantees/marriages do not get +20 bonus
- T6: Noble Electors - Unknown Origins, can't test
- T6: Royal Electors - Unknown Origins, can't test
- T6: Parliamental Electors - Unknown Origins, can't test
- T6: Papal Electors - Unknown Origins, can't test
