### ISSUE TITLE
Suggestion to fix muslim piety

### ISSUE THREAD

**Issue by Thorfindel** [vikingnephilim/VikingShattered#36]
Goal: make Muslim republics viable by lowering loss of piety at ruler death. 
Goal 1: make Muslim DOWs interact more logically with peity by flipping piety loss/gain when you DOW (non-)Muslims.

Current state, found in defines.lua:
```
	PIETY_PERCENTAGE_AT_NEW_RULER = 0.25,			-- percentage of piety kept at new ruler.
	PIETY_INCREASE_AT_GOOD_WAR = 0.25,
	PIETY_DECREASE_AT_BAD_WAR = -0.33,
```

Suggestion to change to:
```
	PIETY_PERCENTAGE_AT_NEW_RULER = 080,			-- percentage of piety kept at new ruler.
	PIETY_INCREASE_AT_GOOD_WAR = -0.25,
	PIETY_DECREASE_AT_BAD_WAR = 0.25,
```

**Comment by vikingnephilim** [comment]
added by you!
