### ISSUE TITLE
Knight templar ideas

### ISSUE THREAD

**Issue by Feuerhai** [vikingnephilim/VikingShattered#42]
Just a note so we don't forget: 
Knight templar ideas are op (10% Discipline) and might need a nerf.
Traditions:
+1 Diplomatic reputation
+1 Tolerance of heathens
Latin Rule
+10% Discipline
Letters of Credit
+20% National tax modifier
Assault Troops of the Crusades
+10% Cavalry combat ability
Bank Of Europe
+0.10 Yearly inflation reduction
The Templar Enterprise
+20% Production efficiency
The Supporting Infrastructure
+1 Possible advisor
Crusader Traditions
+1 Leader without upkeep
Ambition:
+25% National manpower modifier

**Comment by Thorfindel** [comment]
Suggested change:
+5% disc instead of +10%
+15% tax instead of +20% (something little unique to make them fancy)
+10% prod instead of +20%
+20% manpower instead of +25%

**Comment by vikingnephilim** [comment]
If you want to make the mod to the file, by all means 👍
