### ISSUE TITLE
Suggestion: +2 monthly fervor per stab

### ISSUE THREAD

**Issue by Thorfindel** [vikingnephilim/VikingShattered#43]
**Suggestion**: increase fervor gain from stab to +2 instead of +1.
**Context**: the max fervor you can have +8 per month, at 3 stab, 100 prestige, 100 RU, max happy clergy and at peace. So during war it's 7. And Geneva can get to +9 due their NI. This makes micromanaging 2 fervor choices a bit annoying, with one always switching off unknowingly. 
**Effect of change**: At 3 stab you'll now get +6 instead of +3. This means you end up at +11 when at peace and +10 during war. In terms of balance, I believe giving fervor religions the ability to always have 2 abilities on at all times a good thing. Reminder: you still need 100% RU, 100 prestige and max happy clergy to get this, so it's still not trivial.

**Comment by vikingnephilim** [comment]
If you want to make the mod to the files, by all means 👍
